/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin/activity'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin/companies'
import { Route as AuthenticatedAdminLocationsRouteImport } from './routes/_authenticated/admin/locations'
import { Route as AuthenticatedAdminMaterialsRouteImport } from './routes/_authenticated/admin/materials'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTransportersRouteImport } from './routes/_authenticated/admin/transporters'
import { Route as AuthenticatedAdminVehiclesRouteImport } from './routes/_authenticated/admin/vehicles'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/app/activity'
import { Route as AuthenticatedAppArchiveRouteImport } from './routes/_authenticated/app/archive'
import { Route as AuthenticatedAppCompaniesRouteImport } from './routes/_authenticated/app/companies'
import { Route as AuthenticatedAppTransportersRouteImport } from './routes/_authenticated/app/transporters'
import { Route as AuthenticatedAppVendorsRouteImport } from './routes/_authenticated/app/vendors'
import { Route as AuthenticatedAdminDriversIndexRouteImport } from './routes/_authenticated/admin/drivers/index'
import { Route as AuthenticatedAdminDriversDriverIdRouteImport } from './routes/_authenticated/admin/drivers/$driverId'
import { Route as AuthenticatedAdminDriversNewRouteImport } from './routes/_authenticated/admin/drivers/new'
import { Route as AuthenticatedAdminMembersIndexRouteImport } from './routes/_authenticated/admin/members/index'
import { Route as AuthenticatedAdminMembersMemberIdRouteImport } from './routes/_authenticated/admin/members/$memberId'
import { Route as AuthenticatedAdminMembersNewRouteImport } from './routes/_authenticated/admin/members/new'
import { Route as AuthenticatedAdminVendorsIndexRouteImport } from './routes/_authenticated/admin/vendors/index'
import { Route as AuthenticatedAdminVendorsVendorIdRouteImport } from './routes/_authenticated/admin/vendors/$vendorId'
import { Route as AuthenticatedAdminVendorsNewRouteImport } from './routes/_authenticated/admin/vendors/new'
import { Route as AuthenticatedAppDealsIndexRouteImport } from './routes/_authenticated/app/deals/index'
import { Route as AuthenticatedAppDealsDealIdRouteImport } from './routes/_authenticated/app/deals/$dealId'
import { Route as AuthenticatedAppDealsNewRouteImport } from './routes/_authenticated/app/deals/new'
import { Route as AuthenticatedAppTripsIndexRouteImport } from './routes/_authenticated/app/trips/index'
import { Route as AuthenticatedAppTripsTripIdRouteImport } from './routes/_authenticated/app/trips/$tripId'
import { Route as AuthenticatedAppDealsDealIdTripsNewRouteImport } from './routes/_authenticated/app/deals/$dealId/trips/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLocationsRoute =
  AuthenticatedAdminLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMaterialsRoute =
  AuthenticatedAdminMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTransportersRoute =
  AuthenticatedAdminTransportersRouteImport.update({
    id: '/transporters',
    path: '/transporters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVehiclesRoute =
  AuthenticatedAdminVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppArchiveRoute = AuthenticatedAppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCompaniesRoute =
  AuthenticatedAppCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTransportersRoute =
  AuthenticatedAppTransportersRouteImport.update({
    id: '/transporters',
    path: '/transporters',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVendorsRoute = AuthenticatedAppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminDriversIndexRoute =
  AuthenticatedAdminDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDriversDriverIdRoute =
  AuthenticatedAdminDriversDriverIdRouteImport.update({
    id: '/drivers/$driverId',
    path: '/drivers/$driverId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDriversNewRoute =
  AuthenticatedAdminDriversNewRouteImport.update({
    id: '/drivers/new',
    path: '/drivers/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersIndexRoute =
  AuthenticatedAdminMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersMemberIdRoute =
  AuthenticatedAdminMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersNewRoute =
  AuthenticatedAdminMembersNewRouteImport.update({
    id: '/members/new',
    path: '/members/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVendorsIndexRoute =
  AuthenticatedAdminVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVendorsVendorIdRoute =
  AuthenticatedAdminVendorsVendorIdRouteImport.update({
    id: '/vendors/$vendorId',
    path: '/vendors/$vendorId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVendorsNewRoute =
  AuthenticatedAdminVendorsNewRouteImport.update({
    id: '/vendors/new',
    path: '/vendors/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppDealsIndexRoute =
  AuthenticatedAppDealsIndexRouteImport.update({
    id: '/deals/',
    path: '/deals/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDealsDealIdRoute =
  AuthenticatedAppDealsDealIdRouteImport.update({
    id: '/deals/$dealId',
    path: '/deals/$dealId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDealsNewRoute =
  AuthenticatedAppDealsNewRouteImport.update({
    id: '/deals/new',
    path: '/deals/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTripsIndexRoute =
  AuthenticatedAppTripsIndexRouteImport.update({
    id: '/trips/',
    path: '/trips/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTripsTripIdRoute =
  AuthenticatedAppTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDealsDealIdTripsNewRoute =
  AuthenticatedAppDealsDealIdTripsNewRouteImport.update({
    id: '/trips/new',
    path: '/trips/new',
    getParentRoute: () => AuthenticatedAppDealsDealIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/driver': typeof AuthenticatedDriverRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/transporters': typeof AuthenticatedAdminTransportersRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/archive': typeof AuthenticatedAppArchiveRoute
  '/app/companies': typeof AuthenticatedAppCompaniesRoute
  '/app/transporters': typeof AuthenticatedAppTransportersRoute
  '/app/vendors': typeof AuthenticatedAppVendorsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/drivers/$driverId': typeof AuthenticatedAdminDriversDriverIdRoute
  '/admin/drivers/new': typeof AuthenticatedAdminDriversNewRoute
  '/admin/members/$memberId': typeof AuthenticatedAdminMembersMemberIdRoute
  '/admin/members/new': typeof AuthenticatedAdminMembersNewRoute
  '/admin/vendors/$vendorId': typeof AuthenticatedAdminVendorsVendorIdRoute
  '/admin/vendors/new': typeof AuthenticatedAdminVendorsNewRoute
  '/app/deals/$dealId': typeof AuthenticatedAppDealsDealIdRouteWithChildren
  '/app/deals/new': typeof AuthenticatedAppDealsNewRoute
  '/app/trips/$tripId': typeof AuthenticatedAppTripsTripIdRoute
  '/admin/drivers/': typeof AuthenticatedAdminDriversIndexRoute
  '/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
  '/admin/vendors/': typeof AuthenticatedAdminVendorsIndexRoute
  '/app/deals/': typeof AuthenticatedAppDealsIndexRoute
  '/app/trips/': typeof AuthenticatedAppTripsIndexRoute
  '/app/deals/$dealId/trips/new': typeof AuthenticatedAppDealsDealIdTripsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/transporters': typeof AuthenticatedAdminTransportersRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/archive': typeof AuthenticatedAppArchiveRoute
  '/app/companies': typeof AuthenticatedAppCompaniesRoute
  '/app/transporters': typeof AuthenticatedAppTransportersRoute
  '/app/vendors': typeof AuthenticatedAppVendorsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/drivers/$driverId': typeof AuthenticatedAdminDriversDriverIdRoute
  '/admin/drivers/new': typeof AuthenticatedAdminDriversNewRoute
  '/admin/members/$memberId': typeof AuthenticatedAdminMembersMemberIdRoute
  '/admin/members/new': typeof AuthenticatedAdminMembersNewRoute
  '/admin/vendors/$vendorId': typeof AuthenticatedAdminVendorsVendorIdRoute
  '/admin/vendors/new': typeof AuthenticatedAdminVendorsNewRoute
  '/app/deals/$dealId': typeof AuthenticatedAppDealsDealIdRouteWithChildren
  '/app/deals/new': typeof AuthenticatedAppDealsNewRoute
  '/app/trips/$tripId': typeof AuthenticatedAppTripsTripIdRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversIndexRoute
  '/admin/members': typeof AuthenticatedAdminMembersIndexRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsIndexRoute
  '/app/deals': typeof AuthenticatedAppDealsIndexRoute
  '/app/trips': typeof AuthenticatedAppTripsIndexRoute
  '/app/deals/$dealId/trips/new': typeof AuthenticatedAppDealsDealIdTripsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/_authenticated/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/transporters': typeof AuthenticatedAdminTransportersRoute
  '/_authenticated/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/_authenticated/app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/app/archive': typeof AuthenticatedAppArchiveRoute
  '/_authenticated/app/companies': typeof AuthenticatedAppCompaniesRoute
  '/_authenticated/app/transporters': typeof AuthenticatedAppTransportersRoute
  '/_authenticated/app/vendors': typeof AuthenticatedAppVendorsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/drivers/$driverId': typeof AuthenticatedAdminDriversDriverIdRoute
  '/_authenticated/admin/drivers/new': typeof AuthenticatedAdminDriversNewRoute
  '/_authenticated/admin/members/$memberId': typeof AuthenticatedAdminMembersMemberIdRoute
  '/_authenticated/admin/members/new': typeof AuthenticatedAdminMembersNewRoute
  '/_authenticated/admin/vendors/$vendorId': typeof AuthenticatedAdminVendorsVendorIdRoute
  '/_authenticated/admin/vendors/new': typeof AuthenticatedAdminVendorsNewRoute
  '/_authenticated/app/deals/$dealId': typeof AuthenticatedAppDealsDealIdRouteWithChildren
  '/_authenticated/app/deals/new': typeof AuthenticatedAppDealsNewRoute
  '/_authenticated/app/trips/$tripId': typeof AuthenticatedAppTripsTripIdRoute
  '/_authenticated/admin/drivers/': typeof AuthenticatedAdminDriversIndexRoute
  '/_authenticated/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
  '/_authenticated/admin/vendors/': typeof AuthenticatedAdminVendorsIndexRoute
  '/_authenticated/app/deals/': typeof AuthenticatedAppDealsIndexRoute
  '/_authenticated/app/trips/': typeof AuthenticatedAppTripsIndexRoute
  '/_authenticated/app/deals/$dealId/trips/new': typeof AuthenticatedAppDealsDealIdTripsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/app'
    | '/driver'
    | '/vendor'
    | '/admin/activity'
    | '/admin/companies'
    | '/admin/locations'
    | '/admin/materials'
    | '/admin/settings'
    | '/admin/transporters'
    | '/admin/vehicles'
    | '/app/activity'
    | '/app/archive'
    | '/app/companies'
    | '/app/transporters'
    | '/app/vendors'
    | '/admin/'
    | '/app/'
    | '/admin/drivers/$driverId'
    | '/admin/drivers/new'
    | '/admin/members/$memberId'
    | '/admin/members/new'
    | '/admin/vendors/$vendorId'
    | '/admin/vendors/new'
    | '/app/deals/$dealId'
    | '/app/deals/new'
    | '/app/trips/$tripId'
    | '/admin/drivers/'
    | '/admin/members/'
    | '/admin/vendors/'
    | '/app/deals/'
    | '/app/trips/'
    | '/app/deals/$dealId/trips/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/driver'
    | '/vendor'
    | '/admin/activity'
    | '/admin/companies'
    | '/admin/locations'
    | '/admin/materials'
    | '/admin/settings'
    | '/admin/transporters'
    | '/admin/vehicles'
    | '/app/activity'
    | '/app/archive'
    | '/app/companies'
    | '/app/transporters'
    | '/app/vendors'
    | '/admin'
    | '/app'
    | '/admin/drivers/$driverId'
    | '/admin/drivers/new'
    | '/admin/members/$memberId'
    | '/admin/members/new'
    | '/admin/vendors/$vendorId'
    | '/admin/vendors/new'
    | '/app/deals/$dealId'
    | '/app/deals/new'
    | '/app/trips/$tripId'
    | '/admin/drivers'
    | '/admin/members'
    | '/admin/vendors'
    | '/app/deals'
    | '/app/trips'
    | '/app/deals/$dealId/trips/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/driver'
    | '/_authenticated/vendor'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/locations'
    | '/_authenticated/admin/materials'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/transporters'
    | '/_authenticated/admin/vehicles'
    | '/_authenticated/app/activity'
    | '/_authenticated/app/archive'
    | '/_authenticated/app/companies'
    | '/_authenticated/app/transporters'
    | '/_authenticated/app/vendors'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/drivers/$driverId'
    | '/_authenticated/admin/drivers/new'
    | '/_authenticated/admin/members/$memberId'
    | '/_authenticated/admin/members/new'
    | '/_authenticated/admin/vendors/$vendorId'
    | '/_authenticated/admin/vendors/new'
    | '/_authenticated/app/deals/$dealId'
    | '/_authenticated/app/deals/new'
    | '/_authenticated/app/trips/$tripId'
    | '/_authenticated/admin/drivers/'
    | '/_authenticated/admin/members/'
    | '/_authenticated/admin/vendors/'
    | '/_authenticated/app/deals/'
    | '/_authenticated/app/trips/'
    | '/_authenticated/app/deals/$dealId/trips/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/locations': {
      id: '/_authenticated/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AuthenticatedAdminLocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/materials': {
      id: '/_authenticated/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AuthenticatedAdminMaterialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transporters': {
      id: '/_authenticated/admin/transporters'
      path: '/transporters'
      fullPath: '/admin/transporters'
      preLoaderRoute: typeof AuthenticatedAdminTransportersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vehicles': {
      id: '/_authenticated/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/activity': {
      id: '/_authenticated/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/archive': {
      id: '/_authenticated/app/archive'
      path: '/archive'
      fullPath: '/app/archive'
      preLoaderRoute: typeof AuthenticatedAppArchiveRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/companies': {
      id: '/_authenticated/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AuthenticatedAppCompaniesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/transporters': {
      id: '/_authenticated/app/transporters'
      path: '/transporters'
      fullPath: '/app/transporters'
      preLoaderRoute: typeof AuthenticatedAppTransportersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vendors': {
      id: '/_authenticated/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AuthenticatedAppVendorsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/drivers/': {
      id: '/_authenticated/admin/drivers/'
      path: '/drivers'
      fullPath: '/admin/drivers/'
      preLoaderRoute: typeof AuthenticatedAdminDriversIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drivers/$driverId': {
      id: '/_authenticated/admin/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/admin/drivers/$driverId'
      preLoaderRoute: typeof AuthenticatedAdminDriversDriverIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drivers/new': {
      id: '/_authenticated/admin/drivers/new'
      path: '/drivers/new'
      fullPath: '/admin/drivers/new'
      preLoaderRoute: typeof AuthenticatedAdminDriversNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members/': {
      id: '/_authenticated/admin/members/'
      path: '/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AuthenticatedAdminMembersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members/$memberId': {
      id: '/_authenticated/admin/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/admin/members/$memberId'
      preLoaderRoute: typeof AuthenticatedAdminMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members/new': {
      id: '/_authenticated/admin/members/new'
      path: '/members/new'
      fullPath: '/admin/members/new'
      preLoaderRoute: typeof AuthenticatedAdminMembersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vendors/': {
      id: '/_authenticated/admin/vendors/'
      path: '/vendors'
      fullPath: '/admin/vendors/'
      preLoaderRoute: typeof AuthenticatedAdminVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vendors/$vendorId': {
      id: '/_authenticated/admin/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/admin/vendors/$vendorId'
      preLoaderRoute: typeof AuthenticatedAdminVendorsVendorIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vendors/new': {
      id: '/_authenticated/admin/vendors/new'
      path: '/vendors/new'
      fullPath: '/admin/vendors/new'
      preLoaderRoute: typeof AuthenticatedAdminVendorsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/deals/': {
      id: '/_authenticated/app/deals/'
      path: '/deals'
      fullPath: '/app/deals/'
      preLoaderRoute: typeof AuthenticatedAppDealsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deals/$dealId': {
      id: '/_authenticated/app/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/app/deals/$dealId'
      preLoaderRoute: typeof AuthenticatedAppDealsDealIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deals/new': {
      id: '/_authenticated/app/deals/new'
      path: '/deals/new'
      fullPath: '/app/deals/new'
      preLoaderRoute: typeof AuthenticatedAppDealsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trips/': {
      id: '/_authenticated/app/trips/'
      path: '/trips'
      fullPath: '/app/trips/'
      preLoaderRoute: typeof AuthenticatedAppTripsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trips/$tripId': {
      id: '/_authenticated/app/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/app/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedAppTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deals/$dealId/trips/new': {
      id: '/_authenticated/app/deals/$dealId/trips/new'
      path: '/trips/new'
      fullPath: '/app/deals/$dealId/trips/new'
      preLoaderRoute: typeof AuthenticatedAppDealsDealIdTripsNewRouteImport
      parentRoute: typeof AuthenticatedAppDealsDealIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminLocationsRoute: typeof AuthenticatedAdminLocationsRoute
  AuthenticatedAdminMaterialsRoute: typeof AuthenticatedAdminMaterialsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTransportersRoute: typeof AuthenticatedAdminTransportersRoute
  AuthenticatedAdminVehiclesRoute: typeof AuthenticatedAdminVehiclesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminDriversDriverIdRoute: typeof AuthenticatedAdminDriversDriverIdRoute
  AuthenticatedAdminDriversNewRoute: typeof AuthenticatedAdminDriversNewRoute
  AuthenticatedAdminMembersMemberIdRoute: typeof AuthenticatedAdminMembersMemberIdRoute
  AuthenticatedAdminMembersNewRoute: typeof AuthenticatedAdminMembersNewRoute
  AuthenticatedAdminVendorsVendorIdRoute: typeof AuthenticatedAdminVendorsVendorIdRoute
  AuthenticatedAdminVendorsNewRoute: typeof AuthenticatedAdminVendorsNewRoute
  AuthenticatedAdminDriversIndexRoute: typeof AuthenticatedAdminDriversIndexRoute
  AuthenticatedAdminMembersIndexRoute: typeof AuthenticatedAdminMembersIndexRoute
  AuthenticatedAdminVendorsIndexRoute: typeof AuthenticatedAdminVendorsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminLocationsRoute: AuthenticatedAdminLocationsRoute,
  AuthenticatedAdminMaterialsRoute: AuthenticatedAdminMaterialsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTransportersRoute: AuthenticatedAdminTransportersRoute,
  AuthenticatedAdminVehiclesRoute: AuthenticatedAdminVehiclesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminDriversDriverIdRoute:
    AuthenticatedAdminDriversDriverIdRoute,
  AuthenticatedAdminDriversNewRoute: AuthenticatedAdminDriversNewRoute,
  AuthenticatedAdminMembersMemberIdRoute:
    AuthenticatedAdminMembersMemberIdRoute,
  AuthenticatedAdminMembersNewRoute: AuthenticatedAdminMembersNewRoute,
  AuthenticatedAdminVendorsVendorIdRoute:
    AuthenticatedAdminVendorsVendorIdRoute,
  AuthenticatedAdminVendorsNewRoute: AuthenticatedAdminVendorsNewRoute,
  AuthenticatedAdminDriversIndexRoute: AuthenticatedAdminDriversIndexRoute,
  AuthenticatedAdminMembersIndexRoute: AuthenticatedAdminMembersIndexRoute,
  AuthenticatedAdminVendorsIndexRoute: AuthenticatedAdminVendorsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppDealsDealIdRouteChildren {
  AuthenticatedAppDealsDealIdTripsNewRoute: typeof AuthenticatedAppDealsDealIdTripsNewRoute
}

const AuthenticatedAppDealsDealIdRouteChildren: AuthenticatedAppDealsDealIdRouteChildren =
  {
    AuthenticatedAppDealsDealIdTripsNewRoute:
      AuthenticatedAppDealsDealIdTripsNewRoute,
  }

const AuthenticatedAppDealsDealIdRouteWithChildren =
  AuthenticatedAppDealsDealIdRoute._addFileChildren(
    AuthenticatedAppDealsDealIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppArchiveRoute: typeof AuthenticatedAppArchiveRoute
  AuthenticatedAppCompaniesRoute: typeof AuthenticatedAppCompaniesRoute
  AuthenticatedAppTransportersRoute: typeof AuthenticatedAppTransportersRoute
  AuthenticatedAppVendorsRoute: typeof AuthenticatedAppVendorsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppDealsDealIdRoute: typeof AuthenticatedAppDealsDealIdRouteWithChildren
  AuthenticatedAppDealsNewRoute: typeof AuthenticatedAppDealsNewRoute
  AuthenticatedAppTripsTripIdRoute: typeof AuthenticatedAppTripsTripIdRoute
  AuthenticatedAppDealsIndexRoute: typeof AuthenticatedAppDealsIndexRoute
  AuthenticatedAppTripsIndexRoute: typeof AuthenticatedAppTripsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppArchiveRoute: AuthenticatedAppArchiveRoute,
  AuthenticatedAppCompaniesRoute: AuthenticatedAppCompaniesRoute,
  AuthenticatedAppTransportersRoute: AuthenticatedAppTransportersRoute,
  AuthenticatedAppVendorsRoute: AuthenticatedAppVendorsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppDealsDealIdRoute:
    AuthenticatedAppDealsDealIdRouteWithChildren,
  AuthenticatedAppDealsNewRoute: AuthenticatedAppDealsNewRoute,
  AuthenticatedAppTripsTripIdRoute: AuthenticatedAppTripsTripIdRoute,
  AuthenticatedAppDealsIndexRoute: AuthenticatedAppDealsIndexRoute,
  AuthenticatedAppTripsIndexRoute: AuthenticatedAppTripsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
